#include <QApplication>
#include <QMainWindow>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QWidget>
#include <QLabel>
#include <QPushButton>
#include <QLineEdit>
#include <QFrame>
#include <QStackedWidget>
#include <QCheckBox>
#include <QComboBox>
#include <QProgressBar>
#include <QScrollArea>
#include <QListWidget>
#include <QListWidgetItem>
#include <QTimer>
#include <QDebug>
#include <QRandomGenerator>
#include <QDateTime>
#include <QCloseEvent>
#include <QPainter>
#include <QThread>
#include <QTime>
#include <QSlider>
#include <QSpinBox>
#include <QGroupBox>
#include <QTabWidget>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QHeaderView>

// Network includes for REAL stock data
#include <QNetworkAccessManager>
#include <QNetworkRequest>
#include <QNetworkReply>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QUrl>
